- hosts: tag_application_cassandra
  become: true
  vars:
    cassandra_configuration:
      authenticator: PasswordAuthenticator
      cluster_name: TestCluster
      commitlog_directory: /data/cassandra/commitlog
      commitlog_sync: periodic
      commitlog_sync_period_in_ms: 10000
      data_file_directories:
        - /data/cassandra/data
      endpoint_snitch: GossipingPropertyFileSnitch
      hints_directory: "/data/cassandra/hints"
      listen_address: "{{ ansible_default_ipv4.address }}"
      partitioner: org.apache.cassandra.dht.Murmur3Partitioner
      saved_caches_directory: /data/cassandra/saved_caches
      seed_provider:
        - class_name: "org.apache.cassandra.locator.SimpleSeedProvider"
          parameters:
            - seeds: "{{ ansible_default_ipv4.address }}"
      start_native_transport: true
    cassandra_configure_apache_repo: true
    cassandra_dc: DC1
    cassandra_directories:
      root:
        group: root
        mode: "0755"
        owner: root
        paths:
          - /data
      data:
        paths:
          - /data/cassandra
          - /data/cassandra/commitlog
          - /data/cassandra/data
          - /data/cassandra/hints
          - /data/cassandra/saved_caches
    cassandra_rack: RACK1
    cassandra_repo_apache_release: 311x
  
  pre_tasks:
    - name: Disable Cassandra Restart
      set_fact:
        cassandra_service_restart: False
      when:
        - ansible_os_family == 'Debian'
        - ansible_distribution_major_version == '10'
  roles:
    - role: locp.cassandra